#!/bin/bash

CONTAINER="oglinuk/ddoom:0.1.0"
NAME="ddoom-container"


build() {
	docker build . -t $CONTAINER
}

container() {
	if [[ -n $(docker ps -a | grep $NAME) ]];then
		clean
	fi

	xhost local:root
	docker run -it \
		-e "DISPLAY=unix${DISPLAY}" \
		-v /tmp/.X11-unix:/tmp/.X11-unix \
		--group-add video \
		--device /dev/dri \
		--name $NAME \
		$CONTAINER
	xhost -local:root
}

clean() {
	docker stop $NAME 
	docker rm $NAME 
}

$*
